;this file for FamiTone2 library generated by text2data tool

kidicarus_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,307,256

.instruments:
	.db $b0 ;instrument $00
	.dw .env1,.env0,.env0
	.db $00
	.db $b0 ;instrument $01
	.dw .env2,.env0,.env0
	.db $00
	.db $30 ;instrument $02
	.dw .env3,.env0,.env0
	.db $00
	.db $30 ;instrument $03
	.dw .env4,.env0,.env0
	.db $00
	.db $b0 ;instrument $04
	.dw .env5,.env0,.env0
	.db $00

.samples:
.env0:
	.db $c0,$00,$00
.env1:
	.db $c6,$c4,$c6,$00,$02
.env2:
	.db $c2,$00,$00
.env3:
	.db $cf,$00,$00
.env4:
	.db $cf,$c8,$c0,$00,$02
.env5:
	.db $c1,$00,$00


.song0ch0:
	.db $fb,$04
.ref0:
	.db $00,$bd
.ref1:
	.db $bf
.song0ch0loop:
.ref2:
	.db $00,$bd
.ref3:
	.db $bf
.ref4:
	.db $80,$3b,$3d,$3b,$3d,$3b,$3d,$3b,$3d,$3b,$3d,$3b,$3d,$3b,$3d,$3b
	.db $3c,$81
.ref5:
	.db $43,$3d,$43,$3d,$43,$3d,$43,$3d,$43,$3d,$43,$3d,$43,$3d,$43,$3c
	.db $81
.ref6:
	.db $3a,$9d,$00,$9d
.ref7:
	.db $bf
.ref8:
	.db $3b,$3d,$3b,$3d,$3b,$3d,$3b,$3d,$3b,$3d,$3b,$3d,$3b,$3d,$3b,$3c
	.db $81
	.db $ff,$11
	.dw .ref5
.ref10:
	.db $3a,$9d,$00,$9d
.ref11:
	.db $bf
.ref12:
	.db $2e,$95,$30,$32,$36,$3a,$3c,$89,$3a,$38,$36,$8b,$38
.ref13:
	.db $3a,$9d,$00,$9d
.ref14:
	.db $bf
	.db $ff,$0d
	.dw .ref12
.ref16:
	.db $3a,$9d,$00,$9d
.ref17:
	.db $bf
.ref18:
	.db $44,$9d,$42,$89,$40,$3e,$3c,$8d
.ref19:
	.db $3a,$9d,$00,$9d
	.db $ff,$08
	.dw .ref18
.ref21:
	.db $3a,$9d,$00,$9d
.ref22:
	.db $39,$3b,$3d,$01,$3a,$89,$38,$36,$32,$8d,$36,$89,$34,$32
.ref23:
	.db $2e,$8d,$00,$ad
.ref24:
	.db $bf
.ref25:
	.db $bf
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.ref26:
	.db $00,$bd
.ref27:
	.db $bf
.song0ch1loop:
.ref28:
	.db $00,$bd
.ref29:
	.db $bf
.ref30:
	.db $00,$82,$3d,$3b,$3d,$3b,$3d,$3b,$3d,$3b,$3d,$3b,$3d,$3b,$3d,$3b
	.db $3d,$3a
.ref31:
	.db $81,$3d,$43,$3d,$43,$3d,$43,$3d,$43,$3d,$43,$3d,$43,$3d,$43,$3d
	.db $42
.ref32:
	.db $00,$bb,$88,$50
.ref33:
	.db $82,$52,$87,$00,$52,$00,$93,$53,$55,$53,$4f,$49,$42,$85
.ref34:
	.db $00,$3d,$3b,$3d,$3b,$3d,$3b,$3d,$3b,$3d,$3b,$3d,$3b,$3d,$3b,$3d
	.db $3a
	.db $ff,$11
	.dw .ref31
.ref36:
	.db $00,$bd
.ref37:
	.db $50,$52,$85,$00,$52,$00,$87,$50,$52,$85,$00,$52,$00,$87,$50,$52
	.db $89,$00
.ref38:
	.db $88,$53,$55,$53,$55,$53,$55,$53,$54,$85,$5b,$55,$5b,$55,$5b,$55
	.db $5a,$81
.ref39:
	.db $83,$55,$53,$55,$53,$55,$53,$54,$85,$5b,$55,$5b,$55,$5b,$55,$5a
	.db $81
	.db $ff,$11
	.dw .ref39
.ref41:
	.db $53,$55,$53,$55,$53,$55,$53,$54,$85,$5b,$55,$5b,$55,$5b,$55,$5a
	.db $81
	.db $ff,$11
	.dw .ref39
	.db $ff,$11
	.dw .ref39
.ref44:
	.db $00,$85,$52,$87,$00,$52,$00,$87,$52,$87,$00,$52,$00,$87,$52,$00
	.db $83
.ref45:
	.db $87,$52,$87,$00,$52,$00,$87,$52,$87,$00,$52,$00,$87,$53,$54,$81
	.db $ff,$11
	.dw .ref44
	.db $ff,$10
	.dw .ref45
.ref48:
	.db $52,$8d,$00,$8d,$50,$8d,$00,$8d
.ref49:
	.db $4a,$8d,$00,$8d,$48,$8d,$00,$8d
.ref50:
	.db $00,$bd
.ref51:
	.db $bf
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.ref52:
	.db $80,$2c,$00,$83,$3a,$00,$83,$2c,$00,$83,$3a,$00,$83,$2c,$00,$83
	.db $3a,$00,$83,$2c,$00,$83,$3a,$00,$83
.ref53:
	.db $2c,$00,$83,$3a,$00,$83,$2c,$00,$83,$3a,$00,$83,$2c,$00,$83,$3a
	.db $00,$83,$2c,$00,$83,$3a,$00,$83
.song0ch2loop:
	.db $ff,$18
	.dw .ref52
	.db $ff,$18
	.dw .ref53
	.db $ff,$18
	.dw .ref53
	.db $ff,$18
	.dw .ref53
	.db $ff,$18
	.dw .ref53
	.db $ff,$18
	.dw .ref53
	.db $ff,$18
	.dw .ref53
	.db $ff,$18
	.dw .ref53
	.db $ff,$18
	.dw .ref53
	.db $ff,$18
	.dw .ref53
	.db $ff,$18
	.dw .ref53
	.db $ff,$18
	.dw .ref53
	.db $ff,$18
	.dw .ref53
	.db $ff,$18
	.dw .ref53
	.db $ff,$18
	.dw .ref53
	.db $ff,$18
	.dw .ref53
	.db $ff,$18
	.dw .ref53
	.db $ff,$18
	.dw .ref53
	.db $ff,$18
	.dw .ref53
	.db $ff,$18
	.dw .ref53
.ref74:
	.db $84,$2c,$00,$83,$3a,$00,$83,$2c,$00,$83,$3a,$00,$83,$2c,$00,$83
	.db $3a,$00,$83,$2c,$00,$83,$3a,$00,$83
.ref75:
	.db $2c,$00,$83,$3a,$00,$b3
	.db $ff,$18
	.dw .ref52
	.db $ff,$18
	.dw .ref53
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.ref78:
	.db $bf
.ref79:
	.db $9f,$86,$1e,$89,$1e,$89,$1e,$85
.song0ch3loop:
.ref80:
	.db $87,$86,$1e,$8d,$1e,$8d,$1e,$8d,$1e,$85
.ref81:
	.db $87,$1e,$8d,$1e,$8d,$1e,$8d,$1e,$85
	.db $ff,$09
	.dw .ref81
	.db $ff,$09
	.dw .ref81
	.db $ff,$09
	.dw .ref81
	.db $ff,$09
	.dw .ref81
	.db $ff,$09
	.dw .ref81
	.db $ff,$09
	.dw .ref81
	.db $ff,$09
	.dw .ref81
	.db $ff,$09
	.dw .ref81
	.db $ff,$09
	.dw .ref81
	.db $ff,$09
	.dw .ref81
	.db $ff,$09
	.dw .ref81
	.db $ff,$09
	.dw .ref81
	.db $ff,$09
	.dw .ref81
	.db $ff,$09
	.dw .ref81
.ref96:
	.db $87,$1e,$00,$8b,$1e,$00,$8b,$1e,$00,$8b,$1e,$00,$83
.ref97:
	.db $87,$1e,$00,$8b,$1e,$00,$8b,$1e,$00,$83,$1e,$00,$1e,$00,$1e,$00
	.db $83
	.db $ff,$0d
	.dw .ref96
	.db $ff,$11
	.dw .ref97
	.db $ff,$0d
	.dw .ref96
.ref101:
	.db $a7,$1e,$00,$83,$1e,$00,$83,$1e,$00,$1e,$00
	.db $ff,$09
	.dw .ref81
	.db $ff,$09
	.dw .ref81
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.ref104:
	.db $36,$95,$36,$85,$36,$9d
.ref105:
	.db $36,$95,$36,$85,$36,$85,$36,$85,$32,$85,$33,$32,$81
.song0ch4loop:
.ref106:
	.db $36,$8d,$32,$8d,$36,$85,$36,$85,$32,$89,$32,$81
.ref107:
	.db $36,$8d,$32,$89,$33,$37,$37,$36,$85,$32,$85,$33,$32,$81
	.db $ff,$0c
	.dw .ref106
	.db $ff,$0e
	.dw .ref107
	.db $ff,$0c
	.dw .ref106
	.db $ff,$0e
	.dw .ref107
	.db $ff,$0c
	.dw .ref106
	.db $ff,$0e
	.dw .ref107
	.db $ff,$0c
	.dw .ref106
	.db $ff,$0e
	.dw .ref107
.ref116:
	.db $36,$8d,$32,$89,$36,$85,$37,$36,$85,$32,$89,$32,$81
.ref117:
	.db $36,$8d,$32,$8d,$36,$85,$36,$85,$32,$8d
	.db $ff,$0d
	.dw .ref116
	.db $ff,$0a
	.dw .ref117
	.db $ff,$0d
	.dw .ref116
	.db $ff,$0a
	.dw .ref117
.ref122:
	.db $36,$8d,$32,$89,$36,$85,$37,$36,$85,$32,$8d
	.db $ff,$0d
	.dw .ref116
	.db $ff,$0b
	.dw .ref122
	.db $ff,$0d
	.dw .ref116
	.db $ff,$0b
	.dw .ref122
.ref127:
	.db $36,$8d,$36,$91,$37,$32,$85,$32,$85,$33,$32,$81
	.db $ff,$0c
	.dw .ref106
	.db $ff,$0e
	.dw .ref107
	.db $fd
	.dw .song0ch4loop
