;this file for FamiTone2 library generated by text2data tool

zeldadungeon_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,194,162

.instruments:
	.db $30 ;instrument $01
	.dw .env1,.env0,.env0
	.db $00
	.db $30 ;instrument $0b
	.dw .env2,.env0,.env0
	.db $00

.samples:
.env0:
	.db $c0,$00,$00
.env1:
	.db $c0,$cf,$00,$01
.env2:
	.db $c0,$cc,$cd,$ce,$cf,$02,$ce,$02,$cd,$02,$cc,$02,$cb,$02,$ca,$02
	.db $c9,$02,$c8,$02,$c7,$02,$c6,$02,$c5,$02,$c4,$02,$c3,$02,$c2,$02
	.db $c1,$c1,$c1,$00,$22


.song0ch0:
	.db $fb,$06
.song0ch0loop:
.ref0:
	.db $00,$82,$47,$51,$47,$51,$47,$51,$47,$51,$45,$51,$45,$51,$45,$51
	.db $45,$51,$43,$51,$43,$51,$43,$51,$43,$51,$41,$51,$41,$51,$41,$51
	.db $41,$51,$41,$4f,$41,$4f,$41,$4f,$41,$4f,$41,$4f,$41,$4f,$41,$4f
	.db $41,$4f,$3f,$45,$45,$51,$4b,$51,$57,$57,$57,$62
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref1:
	.db $82,$41,$4f,$41,$4f,$41,$4f,$41,$4f,$3f,$4f,$3f,$4f,$3f,$4f,$3f
	.db $4f,$3d,$4f,$3d,$4f,$3d,$4f,$3d,$4f,$3b,$4f,$3b,$4f,$3b,$4f,$3b
	.db $4f,$39,$4b,$39,$4b,$39,$4b,$39,$4b,$37,$4b,$37,$4b,$37,$4b,$37
	.db $4b,$33,$45,$3f,$4b,$45,$51,$51,$51,$5d,$5c,$81
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref2:
	.db $80,$40,$8d,$46,$85,$4e,$85,$4c,$85,$3e,$95,$3c,$91,$42,$85,$4d
	.db $4a,$85,$3a,$95,$38,$36,$38,$89,$40,$83,$50,$83,$4f,$36,$34,$36
	.db $89,$40,$83,$4e,$83,$4d,$36,$3e,$44,$3e,$44,$4a,$44,$4a,$50,$4a
	.db $50,$56,$5c,$56,$50,$4a,$50,$4a,$44,$3e
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref3:
	.db $f9,$ed
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref4:
	.db $f9,$ed
	.db $fd
	.dw .song0ch4loop
